import Head from 'next/head';
import Image from 'next/image';
import { Title } from '../components/Title';
import styles from '../styles/pages/supporters.module.scss';

export default function Supporters() {
  return (
    <>
      <Head>
        <title>Apoiadores · Museu Regional de Esportes</title>
        <meta name="title" content="Apoiadores · Museu Regional de Esportes" />
      </Head>
      <main>
        <div className="container content">
          <Title title="Patrocinadores" />
          <section className={styles.supporters}>
            <ul>
              <li>
                <Image
                  src="/shared/supporters/image-1.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-2.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-3.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-4.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-5.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-6.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-7.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-8.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-9.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-10.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-11.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-12.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-13.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-14.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-15.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-16.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-17.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-18.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-19.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-20.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-21.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-22.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-23.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-24.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-25.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-26.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-27.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-28.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-29.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-30.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-31.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-32.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-33.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-34.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-35.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-36.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-37.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-38.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-39.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-40.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-41.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-42.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-43.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-44.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-45.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
            </ul>
          </section>
        </div>
      </main>
    </>
  );
}
