import Head from 'next/head';
import Image from 'next/image';
import { Title } from '../components/Title';
import styles from '../styles/pages/supporters.module.scss';

export default function Supporters() {
  return (
    <>
      <Head>
        <title>Apoiadores · Museu Regional de Esportes</title>
        <meta name="title" content="Apoiadores · Museu Regional de Esportes" />
      </Head>
      <main>
        <div className="container content">
          <Title title="Patrocinadores" />
          <section className={styles.supporters}>
            <ul>
              <li>
                <Image
                  src="/shared/supporters/image-1.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-2.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-3.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-4.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-5.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-6.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-7.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-8.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-9.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-10.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-11.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-12.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-13.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-14.jpg"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
              <li>
                <Image
                  src="/shared/supporters/image-15.png"
                  alt="image"
                  layout="fill"
                  objectFit="cover"
                />
              </li>
            </ul>
          </section>
        </div>
      </main>
    </>
  );
}
